spring:
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.59.159:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 120000

  cloud:
    nacos:
      discovery:
        server-addr: 39.108.59.159:8848
  application:
    name: mall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  thymeleaf:
    cache: false

  redis:
    host: 39.108.59.159
    port: 6379

  # 配置使用redis作为缓存
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      # 是否缓存空值,防止缓存穿透
      cache-null-values: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#      配置全局的逻辑删除规则
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000
logging:
  level:
    com.scut.mall: debug

ipAddr: 39.108.59.159