spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.59.159:8848

  thymeleaf:
    cache: false

  redis:
    host: 39.108.59.159
    port: 6379
  session:
    store-type: redis
server:
  servlet:
    session:
      timeout: 30m
  port: 20000
